### ISSUE TITLE
noApples

### ISSUE THREAD

**Issue by alexanderGGreenberg** [OpenSourceCornell/Spring_2018_WICC_OSC#37]
Implement the funciton in `src/noApples.py` with the following specification:
>you have a vendetta against Apple.  Return the inputted list, with
>every element that contains the substring 'apple' removed.
>ex: ['apple', 'Apple', 'I<3apple', 'banana', 'Microsoft']
>return: ['Apple', 'banana', 'Microsoft']

**Comment by kgioioso** [comment]
I got it!
